### ISSUE TITLE
Regex & TC Validate

### ISSUE THREAD

**Issue by VB10** [ozanzeng/tcno-verification#1]
Selam  
Kullanıcıdan gelen data için regex kullansak daha güzel olurdu (static String _TC_REGEX = r"^[1-9]{1}[0-9]{10}$"; dart'daki bir sample örneği)
Birde validasyonlar eksik gibi geldi referans olarak burayı bakmak gerekiyor sanki 
https://www.hukuki.net/tckimlikdogrulama.php

**Comment by ozanzeng** [comment]
Selam @VB10 , geri bildirimin için teşekkürler.
Önerini bir sonraki geliştirme süreç listesinde uygulamış olacağım. ^_^

**Comment by VB10** [comment]
okey sevgiler iyi çalışmalar
